import { CalendarData } from '@components/calendar/types/calendar';

export const getData = (): CalendarData => ({
    timezone: 'US/Eastern',
    dates: [
        {
            date: '2022-05-15',
            total_cal: 1700.64,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-29',
            total_cal: 94.64,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-23',
            total_cal: 1950,
            total_cal_burned: 400,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-09',
            total_cal: 3200,
            total_cal_burned: 200,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-12',
            total_cal: 2500,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-14',
            total_cal: 1900.64,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-07',
            total_cal: 3900.64,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-01',
            total_cal: 0,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-05',
            total_cal: 4000,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-03',
            total_cal: 2100,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-28',
            total_cal: 94.64,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-27',
            total_cal: 540.14,
            total_cal_burned: 0,
            total_proteins: 34.28,
            total_carbs: 40.27,
            total_fat: 26.56,
            total_sodium: 791,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-26',
            total_cal: 283.92,
            total_cal_burned: 0,
            total_proteins: 1.41,
            total_carbs: 75.39,
            total_fat: 0.93,
            total_sodium: 5.46,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 3,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-20',
            total_cal: 94.64,
            total_cal_burned: 0,
            total_proteins: 0.47,
            total_carbs: 25.13,
            total_fat: 0.31,
            total_sodium: 1.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 1,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-18',
            total_cal: 189.28,
            total_cal_burned: 0,
            total_proteins: 0.94,
            total_carbs: 50.26,
            total_fat: 0.62,
            total_sodium: 3.64,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 2,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
        {
            date: '2022-04-16',
            total_cal: 634.78,
            total_cal_burned: 0,
            total_proteins: 34.75,
            total_carbs: 65.4,
            total_fat: 26.87,
            total_sodium: 792.82,
            water_consumed_liter: null,
            avg_weight_kg: null,
            daily_kcal_limit: 2000,
            daily_carbs_pct: null,
            daily_fat_pct: 98,
            daily_protein_pct: 1,
            foods_logged: 2,
            exercises_logged: null,
            weights_logged: null,
            notes: null,
        },
    ],
});
